import fs from "node:fs";
import path from "node:path";
import { NatTraversalError } from "../domain/errors.mjs";
import { LINK_STATUS } from "../domain/status.mjs";
import {
  createFrpcSupervisor,
  discoverRunningFrpcProcesses,
  isCrossPlatformMismatch,
} from "../process/frpc-supervisor.mjs";
import { validateNatTraversalConfig } from "../domain/config-schema.mjs";
import { discoverFrpcConfigs } from "../infra/frpc-config-io.mjs";

function tomlEscape(value) {
  return String(value ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function renderFrpcToml({ config, token = "", configPathHint = "" }) {
  const cfg = validateNatTraversalConfig(config);
  const lines = [];
  lines.push(`# Generated by Shrimp NAT Traversal`);
  if (configPathHint) lines.push(`# source: ${configPathHint}`);
  lines.push(`serverAddr = "${tomlEscape(cfg.frpc.serverAddr)}"`);
  lines.push(`serverPort = ${Number(cfg.frpc.serverPort)}`);
  if (token) lines.push(`auth.token = "${tomlEscape(token)}"`);
  lines.push(`log.to = "console"`);
  lines.push(`log.level = "${tomlEscape(cfg.frpc.logLevel || "info")}"`);
  lines.push("");
  for (const proxy of cfg.frpc.proxies) {
    lines.push(`[[proxies]]`);
    lines.push(`name = "${tomlEscape(proxy.name)}"`);
    lines.push(`type = "${tomlEscape(proxy.type || "tcp")}"`);
    lines.push(`localIP = "${tomlEscape(proxy.localIp || "127.0.0.1")}"`);
    lines.push(`localPort = ${Number(proxy.localPort)}`);
    lines.push(`remotePort = ${Number(proxy.remotePort)}`);
    lines.push("");
  }
  return `${lines.join("\n").trim()}\n`;
}

export function createFrpcProvider({
  paths,
  logger = console,
  supervisorFactory = createFrpcSupervisor,
  whichBin = defaultWhichBin,
} = {}) {
  let supervisor = null;
  let currentConfig = null;
  let currentToken = "";

  function resolveConfigPath(config) {
    const external = String(config?.frpc?.configPath || "").trim();
    if (external) {
      try {
        if (fs.existsSync(external)) return external;
      } catch {
        // ignore invalid platform path
      }

      if (isCrossPlatformMismatch(external, process.platform)) {
        // Check if an external frpc process is running on this host
        try {
          const running = discoverRunningFrpcProcesses({ platform: process.platform });
          if (running.length && running[0].configPath && fs.existsSync(running[0].configPath)) {
            return running[0].configPath;
          }
        } catch {
          // ignore
        }

        // Check candidate config files on this machine
        try {
          const candidates = discoverFrpcConfigs();
          if (candidates.length && candidates[0].path) {
            return candidates[0].path;
          }
        } catch {
          // ignore
        }
      }

      return external;
    }

    return paths.generatedFrpcConfigPath;
  }

  // Prefer one log file next to the active frpc.toml.
  // Only use gateway nat-traversal/frpc.log for generated configs.
  function resolveLogPath(config) {
    const configPath = resolveConfigPath(config);
    const external = String(config?.frpc?.configPath || "").trim();
    if (configPath && configPath !== paths.generatedFrpcConfigPath) {
      try {
        return path.join(path.dirname(configPath), "frpc.log");
      } catch {
        // ignore
      }
    }
    return paths.logPath;
  }

  function resolveBin(config) {
    const configured = String(config?.frpc?.binPath || "").trim();
    if (configured) {
      try {
        if (fs.existsSync(configured)) return configured;
      } catch {
        // ignore
      }
    }

    // Check running frpc process
    try {
      const running = discoverRunningFrpcProcesses({ platform: process.platform });
      if (running.length && running[0].binPath && fs.existsSync(running[0].binPath)) {
        return running[0].binPath;
      }
    } catch {
      // ignore
    }

    // Prefer frpc sitting next to the selected config file
    // e.g. /Users/pa/frp/frpc.toml -> /Users/pa/frp/frpc
    const configPath = resolveConfigPath(config);
    if (configPath) {
      try {
        const dir = path.dirname(configPath);
        for (const name of process.platform === "win32"
          ? ["frpc.exe", "frpc"]
          : ["frpc"]) {
          const sibling = path.join(dir, name);
          if (fs.existsSync(sibling)) return sibling;
        }
      } catch {
        // continue
      }
    }

    const found = whichBin("frpc");
    if (found) return found;
    return process.platform === "win32" ? "frpc.exe" : "frpc";
  }

  function ensureSupervisor(config) {
    const cfg = config || currentConfig || { frpc: {} };
    const binPath = resolveBin(cfg);
    const configPath = resolveConfigPath(cfg);
    const logPath = resolveLogPath(cfg);
    supervisor = supervisorFactory({
      binPath,
      configPath,
      pidPath: paths.pidPath,
      logPath,
      logger,
    });
    return { supervisor, binPath, configPath, logPath };
  }

  return {
    id: "frpc",
    capabilities() {
      return ["tunnel", "process-control", "config-render", "peer-link-test"];
    },
    resolveConfigPath(config) {
      return resolveConfigPath(config || currentConfig || { frpc: {} });
    },
    resolveBin(config) {
      return resolveBin(config || currentConfig || { frpc: {} });
    },
    validateConfig(config) {
      validateNatTraversalConfig(config);
      return { ok: true };
    },
    async applyConfig(config, { token = "", writeToFile = true } = {}) {
      const cfg = validateNatTraversalConfig(config);
      currentConfig = cfg;
      currentToken = token;
      const { configPath } = ensureSupervisor(cfg);

      let effectiveToken = token;
      if (!effectiveToken && fs.existsSync(configPath)) {
        try {
          const { parsed } = readFrpcConfigFile(configPath);
          if (parsed?.token) effectiveToken = parsed.token;
        } catch {
          // ignore
        }
      }

      if (writeToFile && configPath) {
        fs.mkdirSync(path.dirname(configPath), { recursive: true });
        const body = renderFrpcToml({
          config: cfg,
          token: effectiveToken,
          configPathHint: paths.configPath,
        });
        fs.writeFileSync(configPath, body, "utf8");
        return { configPath, bytes: body.length, mode: "persisted-file" };
      }

      return { configPath, bytes: 0, mode: "no-write" };
    },
    async start(config) {
      if (config) currentConfig = validateNatTraversalConfig(config);
      if (!currentConfig) {
        throw new NatTraversalError(
          "invalid_config",
          "frpc config is required before start",
        );
      }
      const { supervisor: sup } = ensureSupervisor(currentConfig);
      return sup.start();
    },
    async stop(config) {
      if (config) currentConfig = validateNatTraversalConfig(config);
      const { supervisor: sup } = ensureSupervisor(currentConfig || config || { frpc: {} });
      return sup.stop();
    },
    async status(config) {
      if (config) {
        try {
          currentConfig = validateNatTraversalConfig(config);
        } catch {
          currentConfig = config;
        }
      }
      const { supervisor: sup, binPath, configPath } = ensureSupervisor(
        currentConfig || config || { frpc: {} },
      );
      const st = sup.getStatus();
      return {
        ...st,
        binPath,
        configPath,
      };
    },
    async ensureLink(peer) {
      // Phase 1: ensure local provider is running; peer reachability is tested separately.
      const st = await this.status();
      if (st.status !== "running") {
        throw new NatTraversalError(
          "not_running",
          "frpc is not running; start NAT Traversal first",
        );
      }
      return {
        peerId: peer?.id || "",
        provider: "frpc",
        status: LINK_STATUS.online,
        endpoint: peer?.services?.gatewayApi || "",
      };
    },
    async linkStatus(peer) {
      return this.testLink(peer);
    },
    async testLink(peer) {
      if (!peer) {
        throw new NatTraversalError("peer_not_found", "peer is required");
      }
      const target = peer?.services?.gatewayApi || peer?.ssh?.host;
      if (!target) {
        return {
          peerId: peer.id,
          status: LINK_STATUS.unknown,
          message: "no gatewayApi/ssh host configured",
        };
      }

      // Prefer HTTP health if gatewayApi looks like host:port or URL.
      const url = normalizeProbeUrl(peer.services?.gatewayApi);
      if (url) {
        try {
          const res = await fetch(url, { method: "GET" });
          return {
            peerId: peer.id,
            status: res.ok ? LINK_STATUS.online : LINK_STATUS.error,
            httpStatus: res.status,
            url,
          };
        } catch (error) {
          return {
            peerId: peer.id,
            status: LINK_STATUS.offline,
            url,
            message: error.message || String(error),
          };
        }
      }

      return {
        peerId: peer.id,
        status: LINK_STATUS.unknown,
        message: "unsupported peer probe target",
      };
    },
    async openService(peer, service) {
      if (service === "gateway-api") {
        const endpoint = peer?.services?.gatewayApi;
        if (!endpoint) {
          throw new NatTraversalError(
            "invalid_config",
            "peer.services.gatewayApi is required",
          );
        }
        return { service, endpoint };
      }
      throw new NatTraversalError(
        "unsupported_feature",
        `service '${service}' is not supported by frpc provider yet`,
      );
    },
  };
}

function normalizeProbeUrl(value) {
  const raw = String(value || "").trim();
  if (!raw) return "";
  if (raw.startsWith("http://") || raw.startsWith("https://")) return raw;
  if (raw.includes("/")) return `http://${raw}`;
  // host:port -> health endpoint guess on gateway root
  return `http://${raw}/`;
}

function defaultWhichBin(name) {
  const pathEnv = String(process.env.PATH || "");
  const names =
    process.platform === "win32"
      ? [name, `${name}.exe`, `${name}.cmd`]
      : [name];
  for (const dir of pathEnv.split(path.delimiter)) {
    if (!dir) continue;
    for (const fileName of names) {
      const candidate = path.join(dir, fileName);
      try {
        fs.accessSync(candidate, fs.constants.F_OK);
        return candidate;
      } catch {
        // continue
      }
    }
  }
  for (const candidate of [
    `/opt/homebrew/bin/${name}`,
    `/usr/local/bin/${name}`,
  ]) {
    try {
      fs.accessSync(candidate, fs.constants.F_OK);
      return candidate;
    } catch {
      // continue
    }
  }
  return "";
}
