import fs from "node:fs";
import path from "node:path";
import { NatTraversalError } from "../domain/errors.mjs";
import { LINK_STATUS } from "../domain/status.mjs";
import { createFrpcSupervisor } from "../process/frpc-supervisor.mjs";
import { validateNatTraversalConfig } from "../domain/config-schema.mjs";

function tomlEscape(value) {
  return String(value ?? "").replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

export function renderFrpcToml({ config, token = "", configPathHint = "" }) {
  const cfg = validateNatTraversalConfig(config);
  const lines = [];
  lines.push(`# Generated by Shrimp NAT Traversal`);
  if (configPathHint) lines.push(`# source: ${configPathHint}`);
  lines.push(`serverAddr = "${tomlEscape(cfg.frpc.serverAddr)}"`);
  lines.push(`serverPort = ${Number(cfg.frpc.serverPort)}`);
  if (token) lines.push(`auth.token = "${tomlEscape(token)}"`);
  lines.push(`log.to = "console"`);
  lines.push(`log.level = "${tomlEscape(cfg.frpc.logLevel || "info")}"`);
  lines.push("");
  for (const proxy of cfg.frpc.proxies) {
    lines.push(`[[proxies]]`);
    lines.push(`name = "${tomlEscape(proxy.name)}"`);
    lines.push(`type = "${tomlEscape(proxy.type || "tcp")}"`);
    lines.push(`localIP = "${tomlEscape(proxy.localIp || "127.0.0.1")}"`);
    lines.push(`localPort = ${Number(proxy.localPort)}`);
    lines.push(`remotePort = ${Number(proxy.remotePort)}`);
    lines.push("");
  }
  return `${lines.join("\n").trim()}\n`;
}

export function createFrpcProvider({
  paths,
  logger = console,
  supervisorFactory = createFrpcSupervisor,
  whichBin = defaultWhichBin,
} = {}) {
  let supervisor = null;
  let currentConfig = null;
  let currentToken = "";

  function resolveBin(config) {
    const configured = String(config?.frpc?.binPath || "").trim();
    if (configured) return configured;
    const found = whichBin("frpc");
    if (found) return found;
    return process.platform === "win32" ? "frpc.exe" : "frpc";
  }

  function ensureSupervisor(config) {
    const binPath = resolveBin(config);
    const configPath =
      String(config?.frpc?.configPath || "").trim() || paths.generatedFrpcConfigPath;
    supervisor = supervisorFactory({
      binPath,
      configPath,
      pidPath: paths.pidPath,
      logPath: paths.logPath,
      logger,
    });
    return { supervisor, binPath, configPath };
  }

  return {
    id: "frpc",
    capabilities() {
      return ["tunnel", "process-control", "config-render", "peer-link-test"];
    },
    validateConfig(config) {
      validateNatTraversalConfig(config);
      return { ok: true };
    },
    async applyConfig(config, { token = "" } = {}) {
      const cfg = validateNatTraversalConfig(config);
      currentConfig = cfg;
      currentToken = token;
      const { configPath } = ensureSupervisor(cfg);
      const external = String(cfg.frpc?.configPath || "").trim();
      // If user selected an existing frpc config file, run against it directly.
      // Do not rewrite/copy token into secrets or generate a second config.
      if (external && fs.existsSync(external) && path.resolve(external) === path.resolve(configPath)) {
        return { configPath, bytes: fs.statSync(configPath).size, mode: "external-file" };
      }
      fs.mkdirSync(path.dirname(configPath), { recursive: true });
      const body = renderFrpcToml({
        config: cfg,
        token,
        configPathHint: paths.configPath,
      });
      fs.writeFileSync(configPath, body, "utf8");
      return { configPath, bytes: body.length, mode: "generated-file" };
    },
    async start() {
      if (!currentConfig) {
        throw new NatTraversalError(
          "invalid_config",
          "applyConfig must be called before start",
        );
      }
      if (!supervisor) ensureSupervisor(currentConfig);
      return supervisor.start();
    },
    async stop() {
      if (!supervisor) {
        ensureSupervisor(currentConfig || { frpc: {} });
      }
      return supervisor.stop();
    },
    async status() {
      if (!supervisor) {
        const { supervisor: created } = ensureSupervisor(
          currentConfig || { frpc: {} },
        );
        return created.getStatus();
      }
      return supervisor.getStatus();
    },
    async ensureLink(peer) {
      // Phase 1: ensure local provider is running; peer reachability is tested separately.
      const st = await this.status();
      if (st.status !== "running") {
        throw new NatTraversalError(
          "not_running",
          "frpc is not running; start NAT Traversal first",
        );
      }
      return {
        peerId: peer?.id || "",
        provider: "frpc",
        status: LINK_STATUS.online,
        endpoint: peer?.services?.gatewayApi || "",
      };
    },
    async linkStatus(peer) {
      return this.testLink(peer);
    },
    async testLink(peer) {
      if (!peer) {
        throw new NatTraversalError("peer_not_found", "peer is required");
      }
      const target = peer?.services?.gatewayApi || peer?.ssh?.host;
      if (!target) {
        return {
          peerId: peer.id,
          status: LINK_STATUS.unknown,
          message: "no gatewayApi/ssh host configured",
        };
      }

      // Prefer HTTP health if gatewayApi looks like host:port or URL.
      const url = normalizeProbeUrl(peer.services?.gatewayApi);
      if (url) {
        try {
          const res = await fetch(url, { method: "GET" });
          return {
            peerId: peer.id,
            status: res.ok ? LINK_STATUS.online : LINK_STATUS.error,
            httpStatus: res.status,
            url,
          };
        } catch (error) {
          return {
            peerId: peer.id,
            status: LINK_STATUS.offline,
            url,
            message: error.message || String(error),
          };
        }
      }

      return {
        peerId: peer.id,
        status: LINK_STATUS.unknown,
        message: "unsupported peer probe target",
      };
    },
    async openService(peer, service) {
      if (service === "gateway-api") {
        const endpoint = peer?.services?.gatewayApi;
        if (!endpoint) {
          throw new NatTraversalError(
            "invalid_config",
            "peer.services.gatewayApi is required",
          );
        }
        return { service, endpoint };
      }
      throw new NatTraversalError(
        "unsupported_feature",
        `service '${service}' is not supported by frpc provider yet`,
      );
    },
  };
}

function normalizeProbeUrl(value) {
  const raw = String(value || "").trim();
  if (!raw) return "";
  if (raw.startsWith("http://") || raw.startsWith("https://")) return raw;
  if (raw.includes("/")) return `http://${raw}`;
  // host:port -> health endpoint guess on gateway root
  return `http://${raw}/`;
}

function defaultWhichBin(name) {
  const pathEnv = String(process.env.PATH || "");
  const names =
    process.platform === "win32"
      ? [name, `${name}.exe`, `${name}.cmd`]
      : [name];
  for (const dir of pathEnv.split(path.delimiter)) {
    if (!dir) continue;
    for (const fileName of names) {
      const candidate = path.join(dir, fileName);
      try {
        fs.accessSync(candidate, fs.constants.F_OK);
        return candidate;
      } catch {
        // continue
      }
    }
  }
  for (const candidate of [
    `/opt/homebrew/bin/${name}`,
    `/usr/local/bin/${name}`,
  ]) {
    try {
      fs.accessSync(candidate, fs.constants.F_OK);
      return candidate;
    } catch {
      // continue
    }
  }
  return "";
}
