/**
 * I Ching 64 hexagrams data.
 * Source: ctext.org Book of Changes
 * Contains: judgment, image (Da Xiang Zhuan), lines (Yao Ci + Xiao Xiang Zhuan)
 * Auto-generated. Do not edit manually.
 */

export interface IchingLine {
  position: string;
  text: string;
  commentary: string;
}

export interface IchingHexagram {
  number: number;
  name: string;
  symbol: string;
  pinyin: string;
  upperTrigram: string;
  lowerTrigram: string;
  judgment: string;
  image: string;
  lines: IchingLine[];
}

export const HEXAGRAMS: IchingHexagram[] = [
  {
    number: 1,
    name: "乾",
    symbol: "䷀",
    pinyin: "qian",
    upperTrigram: "乾",
    lowerTrigram: "乾",
    judgment: "乾：元亨，利贞。",
    image: "天行健，君子以自强不息。",
    lines: [
      { position: "初九", text: "潜龙，勿用。", commentary: "潜龙勿用，阳在下也。" },
      { position: "九二", text: "见龙在田，利见大人。", commentary: "见龙在田，德施普也。" },
      { position: "九三", text: "君子终日乾乾，夕惕若，厉，无咎。", commentary: "终日乾乾，反复道也。" },
      { position: "九四", text: "或跃在渊，无咎。", commentary: "或跃在渊，进无咎也。" },
      { position: "九五", text: "飞龙在天，利见大人。", commentary: "飞龙在天，大人造也。" },
      { position: "上九", text: "亢龙有悔。", commentary: "亢龙有悔，盈不可久也。" },
      { position: "用九", text: "见群龙无首，吉。", commentary: "用九，天德不可为首也。" },
    ],
  },
  {
    number: 2,
    name: "坤",
    symbol: "䷁",
    pinyin: "kun",
    upperTrigram: "坤",
    lowerTrigram: "坤",
    judgment: "坤：元亨，利牝马之贞。君子有攸往，先迷后得主，利西南得朋，东北丧朋。安贞，吉。",
    image: "地势坤，君子以厚德载物。",
    lines: [
      { position: "初六", text: "履霜，坚冰至。", commentary: "履霜坚冰，阴始凝也。驯致其道，至坚冰也。" },
      { position: "六二", text: "直，方，大，不习无不利。", commentary: "六二之动，直以方也。不习无不利，地道光也。" },
      { position: "六三", text: "含章可贞。或从王事，无成有终。", commentary: "含章可贞；以时发也。或从王事，知光大也。" },
      { position: "六四", text: "括囊；无咎，无誉。", commentary: "括囊无咎，慎不害也。" },
      { position: "六五", text: "黄裳，元吉。", commentary: "黄裳元吉，文在中也。" },
      { position: "上六", text: "龙战于野，其血玄黄。", commentary: "战龙于野，其道穷也。" },
      { position: "用六", text: "利永贞。", commentary: "用六永贞，以大终也。" },
    ],
  },
  {
    number: 3,
    name: "屯",
    symbol: "䷂",
    pinyin: "zhun",
    upperTrigram: "坎",
    lowerTrigram: "震",
    judgment: "屯：元亨，利贞，勿用有攸往，利建侯。",
    image: "云，雷，屯；君子以经纶。",
    lines: [
      { position: "初九", text: "磐桓；利居贞，利建侯。", commentary: "虽磐桓，志行正也。以贵下贱，大得民也。" },
      { position: "六二", text: "屯如邅如，乘马班如。匪寇婚媾，女子贞不字，十年乃字。", commentary: "六二之难，乘刚也。十年乃字，反常也。" },
      { position: "六三", text: "即鹿无虞，惟入于林中，君子几不如舍，往吝。", commentary: "即鹿无虞，以纵禽也。君子舍之，往吝穷也。" },
      { position: "六四", text: "乘马班如，求婚媾，往吉，无不利。", commentary: "求而往，明也。" },
      { position: "九五", text: "屯其膏，小贞吉，大贞凶。", commentary: "屯其膏，施未光也。" },
      { position: "上六", text: "乘马班如，泣血涟如。", commentary: "泣血涟如，何可长也。" },
    ],
  },
  {
    number: 4,
    name: "蒙",
    symbol: "䷃",
    pinyin: "meng",
    upperTrigram: "艮",
    lowerTrigram: "坎",
    judgment: "蒙：亨。匪我求童蒙，童蒙求我。初筮告，再三渎，渎则不告。利贞。",
    image: "山下出泉，蒙；君子以果行育德。",
    lines: [
      { position: "初六", text: "发蒙，利用刑人，用说桎梏，以往吝。", commentary: "利用刑人，以正法也。" },
      { position: "九二", text: "包蒙吉；纳妇吉；子克家。", commentary: "子克家，刚柔接也。" },
      { position: "六三", text: "勿用取女；见金夫，不有躬，无攸利。", commentary: "勿用取女，行不顺也。" },
      { position: "六四", text: "困蒙，吝。", commentary: "困蒙之吝，独远实也。" },
      { position: "六五", text: "童蒙，吉。", commentary: "童蒙之吉，顺以巽也。" },
      { position: "上九", text: "击蒙；不利为寇，利御寇。", commentary: "利用御寇，上下顺也。" },
    ],
  },
  {
    number: 5,
    name: "需",
    symbol: "䷄",
    pinyin: "xu",
    upperTrigram: "坎",
    lowerTrigram: "乾",
    judgment: "需：有孚，光亨，贞吉。利涉大川。",
    image: "云上于天，需；君子以饮食宴乐。",
    lines: [
      { position: "初九", text: "需于郊。利用恒，无咎。", commentary: "需于郊，不犯难行也。利用恒，无咎；未失常也。" },
      { position: "九二", text: "需于沙。小有言，终吉。", commentary: "需于沙，衍在中也。虽小有言，以终吉也。" },
      { position: "九三", text: "需于泥，致寇至。", commentary: "需于泥，灾在外也。自我致寇，敬慎不败也。" },
      { position: "六四", text: "需于血，出自穴。", commentary: "需于血，顺以听也。" },
      { position: "九五", text: "需于酒食，贞吉。", commentary: "酒食贞吉，以中正也。" },
      { position: "上六", text: "入于穴，有不速之客三人来，敬之终吉。", commentary: "不速之客来，敬之终吉。虽不当位，未大失也。" },
    ],
  },
  {
    number: 6,
    name: "讼",
    symbol: "䷅",
    pinyin: "song",
    upperTrigram: "乾",
    lowerTrigram: "坎",
    judgment: "讼：有孚，窒。惕中吉。终凶。利见大人，不利涉大川。",
    image: "天与水违行，讼；君子以作事谋始。",
    lines: [
      { position: "初六", text: "不永所事，小有言，终吉。", commentary: "不永所事，讼不可长也。虽有小言，其辩明也。" },
      { position: "九二", text: "不克讼，归而逋，其邑人三百户，无眚。", commentary: "不克讼，归而逋也。自下讼上，患至掇也。" },
      { position: "六三", text: "食旧德，贞厉，终吉，或从王事，无成。", commentary: "食旧德，从上吉也。" },
      { position: "九四", text: "不克讼，复即命渝，安贞吉。", commentary: "复即命，渝安贞；不失也。" },
      { position: "九五", text: "讼元吉。", commentary: "讼元吉，以中正也。" },
      { position: "上九", text: "或锡之鞶带，终朝三褫之。", commentary: "以讼受服，亦不足敬也。" },
    ],
  },
  {
    number: 7,
    name: "师",
    symbol: "䷆",
    pinyin: "shi",
    upperTrigram: "坤",
    lowerTrigram: "坎",
    judgment: "师：贞，丈人，吉无咎。",
    image: "地中有水，师；君子以容民畜众。",
    lines: [
      { position: "初六", text: "师出以律，否臧凶。", commentary: "师出以律，失律凶也。" },
      { position: "九二", text: "在师中吉，无咎，王三锡命。", commentary: "在师中吉，承天宠也。王三锡命，怀万邦也。" },
      { position: "六三", text: "师或舆尸，凶。", commentary: "师或舆尸，大无功也。" },
      { position: "六四", text: "师左次，无咎。", commentary: "左次无咎，未失常也。" },
      { position: "六五", text: "田有禽，利执言，无咎。长子帅师，弟子舆尸，贞凶。", commentary: "长子帅师，以中行也。弟子舆尸，使不当也。" },
      { position: "上六", text: "大君有命，开国承家，小人勿用。", commentary: "大君有命，以正功也。小人勿用，必乱邦也。" },
    ],
  },
  {
    number: 8,
    name: "比",
    symbol: "䷇",
    pinyin: "bi",
    upperTrigram: "坎",
    lowerTrigram: "坤",
    judgment: "比：吉。原筮元永贞，无咎。不宁方来，后夫凶。",
    image: "地上有水，比；先王以建万国，亲诸侯。",
    lines: [
      { position: "初六", text: "有孚，比之，无咎。有孚盈缶，终来有它吉。", commentary: "比之初六，有他吉也。" },
      { position: "六二", text: "比之自内，贞吉。", commentary: "比之自内，不自失也。" },
      { position: "六三", text: "比之匪人。", commentary: "比之匪人，不亦伤乎！" },
      { position: "六四", text: "外比之，贞吉。", commentary: "外比于贤，以从上也。" },
      { position: "九五", text: "显比，王用三驱，失前禽。邑人不诫，吉。", commentary: "显比之吉，位正中也。舍逆取顺，失前禽也。邑人不诫，上使中也。" },
      { position: "上六", text: "比之无首，凶。", commentary: "比之无首，无所终也。" },
    ],
  },
  {
    number: 9,
    name: "小畜",
    symbol: "䷈",
    pinyin: "xiao-xu",
    upperTrigram: "巽",
    lowerTrigram: "乾",
    judgment: "小畜：亨。密云不雨，自我西郊。",
    image: "风行天上，小畜；君子以懿文德。",
    lines: [
      { position: "初九", text: "复自道，何其咎，吉。", commentary: "复自道，其义吉也。" },
      { position: "九二", text: "牵复，吉。", commentary: "牵复在中，亦不自失也。" },
      { position: "九三", text: "舆说辐，夫妻反目。", commentary: "夫妻反目，不能正室也。" },
      { position: "六四", text: "有孚，血去惕出，无咎。", commentary: "有孚惕出，上合志也。" },
      { position: "九五", text: "有孚挛如，富以其邻。", commentary: "有孚挛如，不独富也。" },
      { position: "上九", text: "既雨既处，尚德载，妇贞厉。月几望，君子征凶。", commentary: "既雨既处，德积载也。君子征凶，有所疑也。" },
    ],
  },
  {
    number: 10,
    name: "履",
    symbol: "䷉",
    pinyin: "lu",
    upperTrigram: "乾",
    lowerTrigram: "兑",
    judgment: "履虎尾，不咥人，亨。",
    image: "上天下泽，履；君子以辨上下，安民志。",
    lines: [
      { position: "初九", text: "素履，往无咎。", commentary: "素履之往，独行愿也。" },
      { position: "九二", text: "履道坦坦，幽人贞吉。", commentary: "幽人贞吉，中不自乱也。" },
      { position: "六三", text: "眇能视，跛能履，履虎尾，咥人，凶。武人为于大君。", commentary: "眇能视；不足以有明也。跛能履；不足以与行也，咥人之凶；位不当也。武人为于大君；志刚也。" },
      { position: "九四", text: "履虎尾，诉诉，终吉。", commentary: "诉诉终吉，志行也。" },
      { position: "九五", text: "夬履，贞厉。", commentary: "夬履贞厉，位正当也。" },
      { position: "上九", text: "视履考祥，其旋元吉。", commentary: "元吉在上，大有庆也。" },
    ],
  },
  {
    number: 11,
    name: "泰",
    symbol: "䷊",
    pinyin: "tai",
    upperTrigram: "坤",
    lowerTrigram: "乾",
    judgment: "泰：小往大来，吉亨。",
    image: "天地交泰，后以财成天地之道，辅相天地之宜，以左右民。",
    lines: [
      { position: "初九", text: "拔茅茹，以其汇，征吉。", commentary: "拔茅征吉，志在外也。" },
      { position: "九二", text: "包荒，用冯河，不遐遗，朋亡，得尚于中行。", commentary: "包荒，得尚于中行，以光大也。" },
      { position: "九三", text: "无平不陂，无往不复，艰贞无咎。勿恤其孚，于食有福。", commentary: "无往不复，天地际也。" },
      { position: "六四", text: "翩翩，不富，以其邻，不戒以孚。", commentary: "翩翩不富，皆失实也。不戒以孚，中心愿也。" },
      { position: "六五", text: "帝乙归妹，以祉元吉。", commentary: "以祉元吉，中以行愿也。" },
      { position: "上六", text: "城复于隍，勿用师。自邑告命，贞吝。", commentary: "城复于隍，其命乱也。" },
    ],
  },
  {
    number: 12,
    name: "否",
    symbol: "䷋",
    pinyin: "pi",
    upperTrigram: "乾",
    lowerTrigram: "坤",
    judgment: "否之匪人，不利君子贞，大往小来。",
    image: "天地不交，否；君子以俭德辟难，不可荣以禄。",
    lines: [
      { position: "初六", text: "拔茅茹，以其汇，贞吉亨。", commentary: "拔茅贞吉，志在君也。" },
      { position: "六二", text: "包承。小人吉，大人否，亨。", commentary: "大人否亨，不乱群也。" },
      { position: "六三", text: "包羞。", commentary: "包羞，位不当也。" },
      { position: "九四", text: "有命，无咎，畴离祉。", commentary: "有命无咎，志行也。" },
      { position: "九五", text: "休否，大人吉。其亡其亡，系于苞桑。", commentary: "大人之吉，位正当也。" },
      { position: "上九", text: "倾否，先否后喜。", commentary: "否终则倾，何可长也。" },
    ],
  },
  {
    number: 13,
    name: "同人",
    symbol: "䷌",
    pinyin: "tong-ren",
    upperTrigram: "乾",
    lowerTrigram: "离",
    judgment: "同人于野，亨。利涉大川，利君子贞。",
    image: "天与火，同人；君子以类族辨物。",
    lines: [
      { position: "初九", text: "同人于门，无咎。", commentary: "出门同人，又谁咎也。" },
      { position: "六二", text: "同人于宗，吝。", commentary: "同人于宗，吝道也。" },
      { position: "九三", text: "伏戎于莽，升其高陵，三岁不兴。", commentary: "伏戎于莽，敌刚也。三岁不兴，安行也。" },
      { position: "九四", text: "乘其墉，弗克攻，吉。", commentary: "乘其墉，义弗克也，其吉，则困而反则也。" },
      { position: "九五", text: "同人，先号啕而后笑。大师克相遇。", commentary: "同人之先，以中直也。大师相遇，言相克也。" },
      { position: "上九", text: "同人于郊，无悔。", commentary: "同人于郊，志未得也。" },
    ],
  },
  {
    number: 14,
    name: "大有",
    symbol: "䷍",
    pinyin: "da-you",
    upperTrigram: "离",
    lowerTrigram: "乾",
    judgment: "大有：元亨。",
    image: "火在天上，大有；君子以遏恶扬善，顺天休命。",
    lines: [
      { position: "初九", text: "无交害，匪咎，艰则无咎。", commentary: "大有初九，无交害也。" },
      { position: "九二", text: "大车以载，有攸往，无咎。", commentary: "大车以载，积中不败也。" },
      { position: "九三", text: "公用亨于天子，小人弗克。", commentary: "公用亨于天子，小人害也。" },
      { position: "九四", text: "匪其彭，无咎。", commentary: "匪其彭，无咎；明辨晰也。" },
      { position: "六五", text: "厥孚交如，威如；吉。", commentary: "厥孚交如，信以发志也。威如之吉，易而无备也。" },
      { position: "上九", text: "自天佑之，吉无不利。", commentary: "大有上吉，自天佑也。" },
    ],
  },
  {
    number: 15,
    name: "谦",
    symbol: "䷎",
    pinyin: "qian1",
    upperTrigram: "坤",
    lowerTrigram: "艮",
    judgment: "谦：亨，君子有终。",
    image: "地中有山，谦；君子以裒多益寡，称物平施。",
    lines: [
      { position: "初六", text: "谦谦君子，用涉大川，吉。", commentary: "谦谦君子，卑以自牧也。" },
      { position: "六二", text: "鸣谦，贞吉。", commentary: "鸣谦贞吉，中心得也。" },
      { position: "九三", text: "劳谦，君子有终，吉。", commentary: "劳谦君子，万民服也。" },
      { position: "六四", text: "无不利，撝谦。", commentary: "无不利，撝谦；不违则也。" },
      { position: "六五", text: "不富，以其邻，利用侵伐，无不利。", commentary: "利用侵伐，征不服也。" },
      { position: "上六", text: "鸣谦，利用行师，征邑国。", commentary: "鸣谦，志未得也。可用行师，征邑国也。" },
    ],
  },
  {
    number: 16,
    name: "豫",
    symbol: "䷏",
    pinyin: "yu",
    upperTrigram: "震",
    lowerTrigram: "坤",
    judgment: "豫：利建侯，行师。",
    image: "雷出地奋，豫。先王以作乐崇德，殷荐之上帝，以配祖考。",
    lines: [
      { position: "初六", text: "鸣豫，凶。", commentary: "初六鸣豫，志穷凶也。" },
      { position: "六二", text: "介于石，不终日，贞吉。", commentary: "不终日，贞吉；以中正也。" },
      { position: "六三", text: "盱豫，悔。迟有悔。", commentary: "盱豫有悔，位不当也。" },
      { position: "九四", text: "由豫，大有得。勿疑。朋盍簪。", commentary: "由豫，大有得；志大行也。" },
      { position: "六五", text: "贞疾，恒不死。", commentary: "六五贞疾，乘刚也。恒不死，中未亡也。" },
      { position: "上六", text: "冥豫，成有渝，无咎。", commentary: "冥豫在上，何可长也。" },
    ],
  },
  {
    number: 17,
    name: "随",
    symbol: "䷐",
    pinyin: "sui",
    upperTrigram: "兑",
    lowerTrigram: "震",
    judgment: "随：元亨利贞，无咎。",
    image: "泽中有雷，随；君子以向晦入宴息。",
    lines: [
      { position: "初九", text: "官有渝，贞吉。出门交有功。", commentary: "官有渝，从正吉也。出门交有功，不失也。" },
      { position: "六二", text: "系小子，失丈夫。", commentary: "系小子，弗兼与也。" },
      { position: "六三", text: "系丈夫，失小子。随有求得，利居贞。", commentary: "系丈夫，志舍下也。" },
      { position: "九四", text: "随有获，贞凶。有孚在道，以明，何咎。", commentary: "随有获，其义凶也。有孚在道，明功也。" },
      { position: "九五", text: "孚于嘉，吉。", commentary: "孚于嘉，吉；位正中也。" },
      { position: "上六", text: "拘系之，乃从维之。王用亨于西山。", commentary: "拘系之，上穷也。" },
    ],
  },
  {
    number: 18,
    name: "蛊",
    symbol: "䷑",
    pinyin: "gu",
    upperTrigram: "艮",
    lowerTrigram: "巽",
    judgment: "蛊：元亨，利涉大川。先甲三日，后甲三日。",
    image: "山下有风，蛊；君子以振民育德。",
    lines: [
      { position: "初六", text: "干父之蛊，有子，考无咎，厉终吉。", commentary: "干父之蛊，意承考也。" },
      { position: "九二", text: "干母之蛊，不可贞。", commentary: "干母之蛊，得中道也。" },
      { position: "九三", text: "干父之蛊，小有悔，无大咎。", commentary: "干父之蛊，终无咎也。" },
      { position: "六四", text: "裕父之蛊，往见吝。", commentary: "裕父之蛊，往未得也。" },
      { position: "六五", text: "干父之蛊，用誉。", commentary: "干父之蛊；承以德也。" },
      { position: "上九", text: "不事王侯，高尚其事。", commentary: "不事王侯，志可则也。" },
    ],
  },
  {
    number: 19,
    name: "临",
    symbol: "䷒",
    pinyin: "lin",
    upperTrigram: "坤",
    lowerTrigram: "兑",
    judgment: "临：元，亨，利，贞。至于八月有凶。",
    image: "泽上有地，临；君子以教思无穷，容保民无疆。",
    lines: [
      { position: "初九", text: "咸临，贞吉。", commentary: "咸临贞吉，志行正也。" },
      { position: "九二", text: "咸临，吉无不利。", commentary: "咸临，吉无不利；未顺命也。" },
      { position: "六三", text: "甘临，无攸利。既忧之，无咎。", commentary: "甘临，位不当也。既忧之，咎不长也。" },
      { position: "六四", text: "至临，无咎。", commentary: "至临无咎，位当也。" },
      { position: "六五", text: "知临，大君之宜，吉。", commentary: "大君之宜，行中之谓也。" },
      { position: "上六", text: "敦临，吉无咎。", commentary: "敦临之吉，志在内也。" },
    ],
  },
  {
    number: 20,
    name: "观",
    symbol: "䷓",
    pinyin: "guan",
    upperTrigram: "巽",
    lowerTrigram: "坤",
    judgment: "观：盥而不荐，有孚顒若。",
    image: "风行地上，观；先王以省方，观民设教。",
    lines: [
      { position: "初六", text: "童观，小人无咎，君子吝。", commentary: "初六童观，小人道也。" },
      { position: "六二", text: "闚观，利女贞。", commentary: "窥观女贞，亦可丑也。" },
      { position: "六三", text: "观我生，进退。", commentary: "观我生，进退；未失道也。" },
      { position: "六四", text: "观国之光，利用宾于王。", commentary: "观国之光，尚宾也。" },
      { position: "九五", text: "观我生，君子无咎。", commentary: "观我生，观民也。" },
      { position: "上九", text: "观其生，君子无咎。", commentary: "观其生，志未平也。" },
    ],
  },
  {
    number: 21,
    name: "噬嗑",
    symbol: "䷔",
    pinyin: "shi-he",
    upperTrigram: "离",
    lowerTrigram: "震",
    judgment: "噬嗑：亨。利用狱。",
    image: "雷电噬嗑；先王以明罚敕法。",
    lines: [
      { position: "初九", text: "屦校灭趾，无咎。", commentary: "屦校灭趾，不行也。" },
      { position: "六二", text: "噬肤灭鼻，无咎。", commentary: "噬肤灭鼻，乘刚也。" },
      { position: "六三", text: "噬腊肉，遇毒；小吝，无咎。", commentary: "遇毒，位不当也。" },
      { position: "九四", text: "噬乾胏，得金矢，利艰贞，吉。", commentary: "利艰贞吉，未光也。" },
      { position: "六五", text: "噬乾肉，得黄金，贞厉，无咎。", commentary: "贞厉无咎，得当也。" },
      { position: "上九", text: "何校灭耳，凶。", commentary: "何校灭耳，聪不明也。" },
    ],
  },
  {
    number: 22,
    name: "贲",
    symbol: "䷕",
    pinyin: "bi1",
    upperTrigram: "艮",
    lowerTrigram: "离",
    judgment: "贲：亨。小利有攸往。",
    image: "山下有火，贲；君子以明庶政，无敢折狱。",
    lines: [
      { position: "初九", text: "贲其趾，舍车而徒。", commentary: "舍车而徒，义弗乘也。" },
      { position: "六二", text: "贲其须。", commentary: "贲其须，与上兴也。" },
      { position: "九三", text: "贲如濡如，永贞吉。", commentary: "永贞之吉，终莫之陵也。" },
      { position: "六四", text: "贲如皤如，白马翰如，匪寇婚媾。", commentary: "六四，当位疑也。匪寇婚媾，终无尤也。" },
      { position: "六五", text: "贲于丘园，束帛戋戋，吝，终吉。", commentary: "六五之吉，有喜也。" },
      { position: "上九", text: "白贲，无咎。", commentary: "白贲无咎，上得志也。" },
    ],
  },
  {
    number: 23,
    name: "剥",
    symbol: "䷖",
    pinyin: "bo",
    upperTrigram: "艮",
    lowerTrigram: "坤",
    judgment: "剥：不利有攸往。",
    image: "山附地上，剥；上以厚下，安宅。",
    lines: [
      { position: "初六", text: "剥床以足，蔑贞凶。", commentary: "剥床以足，以灭下也。" },
      { position: "六二", text: "剥床以辨，蔑贞凶。", commentary: "剥床以辨，未有与也。" },
      { position: "六三", text: "剥之，无咎。", commentary: "剥之无咎，失上下也。" },
      { position: "六四", text: "剥床以肤，凶。", commentary: "剥床以肤，切近灾也。" },
      { position: "六五", text: "贯鱼，以宫人宠，无不利。", commentary: "以宫人宠，终无尤也。" },
      { position: "上九", text: "硕果不食，君子得舆，小人剥庐。", commentary: "君子得舆，民所载也。小人剥庐，终不可用也。" },
    ],
  },
  {
    number: 24,
    name: "复",
    symbol: "䷗",
    pinyin: "fu",
    upperTrigram: "坤",
    lowerTrigram: "震",
    judgment: "复：亨。出入无疾，朋来无咎。反复其道，七日来复，利有攸往。",
    image: "雷在地中，复；先王以至日闭关，商旅不行，后不省方。",
    lines: [
      { position: "初九", text: "不远复，无祗悔，元吉。", commentary: "不远之复，以修身也。" },
      { position: "六二", text: "休复，吉。", commentary: "休复之吉，以下仁也。" },
      { position: "六三", text: "频复，厉无咎。", commentary: "频复之厉，义无咎也。" },
      { position: "六四", text: "中行独复。", commentary: "中行独复，以从道也。" },
      { position: "六五", text: "敦复，无悔。", commentary: "敦复无悔，中以自考也。" },
      { position: "上六", text: "迷复，凶，有灾眚。用行师，终有大败，以其国君，凶；至于十年，不克征。", commentary: "迷复之凶，反君道也。" },
    ],
  },
  {
    number: 25,
    name: "无妄",
    symbol: "䷘",
    pinyin: "wu-wang",
    upperTrigram: "乾",
    lowerTrigram: "震",
    judgment: "无妄：元亨，利贞。其匪正有眚，不利有攸往。",
    image: "天下雷行，物与无妄；先王以茂对时，育万物。",
    lines: [
      { position: "初九", text: "无妄，往吉。", commentary: "无妄之往，得志也。" },
      { position: "六二", text: "不耕获，不灾畲，则利有攸往。", commentary: "不耕获，未富也。" },
      { position: "六三", text: "无妄之灾，或系之牛，行人之得，邑人之灾。", commentary: "行人得牛，邑人灾也。" },
      { position: "九四", text: "可贞，无咎。", commentary: "可贞无咎，固有之也。" },
      { position: "九五", text: "无妄之疾，勿药有喜。", commentary: "无妄之药，不可试也。" },
      { position: "上九", text: "无妄，行有眚，无攸利。", commentary: "无妄之行，穷之灾也。" },
    ],
  },
  {
    number: 26,
    name: "大畜",
    symbol: "䷙",
    pinyin: "da-xu",
    upperTrigram: "艮",
    lowerTrigram: "乾",
    judgment: "大畜：利贞，不家食吉，利涉大川。",
    image: "天在山中，大畜；君子以多识前言往行，以畜其德。",
    lines: [
      { position: "初九", text: "有厉利已。", commentary: "有厉利已，不犯灾也。" },
      { position: "九二", text: "舆说輹。", commentary: "舆说輹，中无尤也。" },
      { position: "九三", text: "良马逐，利艰贞。曰闲舆卫，利有攸往。", commentary: "利有攸往，上合志也。" },
      { position: "六四", text: "童牛之牿，元吉。", commentary: "六四元吉，有喜也。" },
      { position: "六五", text: "豶豕之牙，吉。", commentary: "六五之吉，有庆也。" },
      { position: "上九", text: "何天之衢，亨。", commentary: "何天之衢，道大行也。" },
    ],
  },
  {
    number: 27,
    name: "颐",
    symbol: "䷚",
    pinyin: "yi",
    upperTrigram: "艮",
    lowerTrigram: "震",
    judgment: "颐：贞吉。观颐，自求口实。",
    image: "山下有雷，颐；君子以慎言语，节饮食。",
    lines: [
      { position: "初九", text: "舍尔灵龟，观我朵颐，凶。", commentary: "观我朵颐，亦不足贵也。" },
      { position: "六二", text: "颠颐，拂经，于丘颐，征凶。", commentary: "六二征凶，行失类也。" },
      { position: "六三", text: "拂颐，贞凶，十年勿用，无攸利。", commentary: "十年勿用，道大悖也。" },
      { position: "六四", text: "颠颐，吉，虎视眈眈，其欲逐逐，无咎。", commentary: "颠颐之吉，上施光也。" },
      { position: "六五", text: "拂经，居贞吉，不可涉大川。", commentary: "居贞之吉，顺以从上也。" },
      { position: "上九", text: "由颐，厉吉，利涉大川。", commentary: "由颐厉吉，大有庆也。" },
    ],
  },
  {
    number: 28,
    name: "大过",
    symbol: "䷛",
    pinyin: "da-guo",
    upperTrigram: "兑",
    lowerTrigram: "巽",
    judgment: "大过：栋桡，利有攸往，亨。",
    image: "泽灭木，大过；君子以独立不惧，遯世无闷。",
    lines: [
      { position: "初六", text: "藉用白茅，无咎。", commentary: "藉用白茅，柔在下也。" },
      { position: "九二", text: "枯杨生稊，老夫得其女妻，无不利。", commentary: "老夫女妻，过以相与也。" },
      { position: "九三", text: "栋桡，凶。", commentary: "栋桡之凶，不可以有辅也。" },
      { position: "九四", text: "栋隆，吉；有它吝。", commentary: "栋隆之吉，不桡乎下也。" },
      { position: "九五", text: "枯杨生华，老妇得士夫，无咎无誉。", commentary: "枯杨生华，何可久也。老妇士夫，亦可丑也。" },
      { position: "上六", text: "过涉灭顶，凶，无咎。", commentary: "过涉之凶，不可咎也。" },
    ],
  },
  {
    number: 29,
    name: "坎",
    symbol: "䷜",
    pinyin: "kan",
    upperTrigram: "坎",
    lowerTrigram: "坎",
    judgment: "坎：习坎，有孚，维心亨，行有尚。",
    image: "水洊至，习坎；君子以常德行，习教事。",
    lines: [
      { position: "初六", text: "习坎，入于坎窞，凶。", commentary: "习坎入坎，失道凶也。" },
      { position: "九二", text: "坎有险，求小得。", commentary: "求小得，未出中也。" },
      { position: "六三", text: "来之坎坎，险且枕，入于坎窞，勿用。", commentary: "来之坎坎，终无功也。" },
      { position: "六四", text: "樽酒簋贰，用缶，纳约自牖，终无咎。", commentary: "樽酒簋贰，刚柔际也。" },
      { position: "九五", text: "坎不盈，祗既平，无咎。", commentary: "坎不盈，中未大也。" },
      { position: "上六", text: "系用徽纆，置于丛棘，三岁不得，凶。", commentary: "上六失道，凶三岁也。" },
    ],
  },
  {
    number: 30,
    name: "离",
    symbol: "䷝",
    pinyin: "li",
    upperTrigram: "离",
    lowerTrigram: "离",
    judgment: "离：利贞，亨。畜牝牛，吉。",
    image: "明两作离，大人以继明照于四方。",
    lines: [
      { position: "初九", text: "履错然，敬之无咎。", commentary: "履错之敬，以辟咎也。" },
      { position: "六二", text: "黄离，元吉。", commentary: "黄离元吉，得中道也。" },
      { position: "九三", text: "日昃之离，不鼓缶而歌，则大耋之嗟，凶。", commentary: "日昃之离，何可久也。" },
      { position: "九四", text: "突如其来如，焚如，死如，弃如。", commentary: "突如其来如，无所容也。" },
      { position: "六五", text: "出涕沱若，戚嗟若，吉。", commentary: "六五之吉，离王公也。" },
      { position: "上九", text: "王用出征，有嘉折首，获匪其丑，无咎。", commentary: "王用出征，以正邦也。" },
    ],
  },
  {
    number: 31,
    name: "咸",
    symbol: "䷞",
    pinyin: "xian",
    upperTrigram: "兑",
    lowerTrigram: "艮",
    judgment: "咸，亨，利贞，取女吉。",
    image: "山上有泽，咸，君子以虚受人。",
    lines: [
      { position: "初六", text: "，咸其拇。", commentary: "咸其拇，志在外也。" },
      { position: "六二", text: "，咸其腓，凶，居吉。", commentary: "虽凶居吉，顺不害也。" },
      { position: "九三", text: "，咸其股，执其随，往吝。", commentary: "咸其股，亦不处也。志在随人，所执下也。" },
      { position: "九四", text: "，贞吉，悔亡，憧憧往来，朋从尔思。", commentary: "贞吉悔亡，未感害也。憧憧往来，未光大也。" },
      { position: "九五", text: "，咸其脢，无悔。", commentary: "咸其脢，志末也。" },
      { position: "上六", text: "，咸其辅颊舌。", commentary: "咸其辅颊舌，滕口说也。" },
    ],
  },
  {
    number: 32,
    name: "恒",
    symbol: "䷟",
    pinyin: "heng",
    upperTrigram: "震",
    lowerTrigram: "巽",
    judgment: "恒：亨，无咎，利贞，利有攸往。",
    image: "雷风，恒；君子以立不易方。",
    lines: [
      { position: "初六", text: "浚恒，贞凶，无攸利。", commentary: "浚恒之凶，始求深也。" },
      { position: "九二", text: "悔亡。", commentary: "九二悔亡，能久中也。" },
      { position: "九三", text: "不恒其德，或承之羞，贞吝。", commentary: "不恒其德，无所容也。" },
      { position: "九四", text: "田无禽。", commentary: "久非其位，安得禽也。" },
      { position: "六五", text: "恒其德，贞，妇人吉，夫子凶。", commentary: "妇人贞吉，从一而终也。夫子制义，从妇凶也。" },
      { position: "上六", text: "振恒，凶。", commentary: "振恒在上，大无功也。" },
    ],
  },
  {
    number: 33,
    name: "遁",
    symbol: "䷠",
    pinyin: "dun",
    upperTrigram: "乾",
    lowerTrigram: "艮",
    judgment: "遯：亨，小利贞。",
    image: "天下有山，遯；君子以远小人，不恶而严。",
    lines: [
      { position: "初六", text: "遯尾，厉，勿用有攸往。", commentary: "遯尾之厉，不往何灾也。" },
      { position: "六二", text: "执之用黄牛之革，莫之胜说。", commentary: "执用黄牛，固志也。" },
      { position: "九三", text: "系遯，有疾厉，畜臣妾吉。", commentary: "系遯之厉，有疾惫也。畜臣妾吉，不可大事也。" },
      { position: "九四", text: "好遯，君子吉，小人否。", commentary: "君子好遯，小人否也。" },
      { position: "九五", text: "嘉遯，贞吉。", commentary: "嘉遯贞吉，以正志也。" },
      { position: "上九", text: "肥遯，无不利。", commentary: "肥遯，无不利；无所疑也。" },
    ],
  },
  {
    number: 34,
    name: "大壮",
    symbol: "䷡",
    pinyin: "da-zhuang",
    upperTrigram: "震",
    lowerTrigram: "乾",
    judgment: "大壮：利贞。",
    image: "雷在天上，大壮；君子以非礼勿履。",
    lines: [
      { position: "初九", text: "壮于趾，征凶，有孚。", commentary: "壮于趾，其孚穷也。" },
      { position: "九二", text: "贞吉。", commentary: "九二贞吉，以中也。" },
      { position: "九三", text: "小人用壮，君子用罔，贞厉。羝羊触藩，羸其角。", commentary: "小人用壮，君子罔也。" },
      { position: "九四", text: "贞吉悔亡，藩决不羸，壮于大舆之輹。", commentary: "藩决不羸，尚往也。" },
      { position: "六五", text: "丧羊于易，无悔。", commentary: "丧羊于易，位不当也。" },
      { position: "上六", text: "羝羊触藩，不能退，不能遂，无攸利，艰则吉。", commentary: "不能退，不能遂，不祥也。艰则吉，咎不长也。" },
    ],
  },
  {
    number: 35,
    name: "晋",
    symbol: "䷢",
    pinyin: "jin",
    upperTrigram: "离",
    lowerTrigram: "坤",
    judgment: "晋：康侯用锡马蕃庶，昼日三接。",
    image: "明出地上，晋；君子以自昭明德。",
    lines: [
      { position: "初六", text: "晋如，摧如，贞吉。罔孚，裕无咎。", commentary: "晋如，摧如；独行正也。裕无咎；未受命也。" },
      { position: "六二", text: "晋如，愁如，贞吉。受兹介福，于其王母。", commentary: "受兹介福，以中正也。" },
      { position: "六三", text: "众允，悔亡。", commentary: "众允之，志上行也。" },
      { position: "九四", text: "晋如硕鼠，贞厉。", commentary: "硕鼠贞厉，位不当也。" },
      { position: "六五", text: "悔亡，失得勿恤，往吉，无不利。", commentary: "失得勿恤，往有庆也。" },
      { position: "上九", text: "晋其角，维用伐邑，厉吉无咎，贞吝。", commentary: "维用伐邑，道未光也。" },
    ],
  },
  {
    number: 36,
    name: "明夷",
    symbol: "䷣",
    pinyin: "ming-yi",
    upperTrigram: "坤",
    lowerTrigram: "离",
    judgment: "明夷：利艰贞。",
    image: "明入地中，明夷；君子以莅众，用晦而明。",
    lines: [
      { position: "初九", text: "明夷于飞，垂其翼。君子于行，三日不食，有攸往，主人有言。", commentary: "君子于行，义不食也。" },
      { position: "六二", text: "明夷，夷于左股，用拯马壮，吉。", commentary: "六二之吉，顺以则也。" },
      { position: "九三", text: "明夷于南狩，得其大首，不可疾贞。", commentary: "南狩之志，乃大得也。" },
      { position: "六四", text: "入于左腹，获明夷之心，出于门庭。", commentary: "入于左腹，获心意也。" },
      { position: "六五", text: "箕子之明夷，利贞。", commentary: "箕子之贞，明不可息也。" },
      { position: "上六", text: "不明晦，初登于天，后入于地。", commentary: "初登于天，照四国也。后入于地，失则也。" },
    ],
  },
  {
    number: 37,
    name: "家人",
    symbol: "䷤",
    pinyin: "jia-ren",
    upperTrigram: "巽",
    lowerTrigram: "离",
    judgment: "家人：利女贞。",
    image: "风自火出，家人；君子以言有物，而行有恒。",
    lines: [
      { position: "初九", text: "闲有家，悔亡。", commentary: "闲有家，志未变也。" },
      { position: "六二", text: "无攸遂，在中馈，贞吉。", commentary: "六二之吉，顺以巽也。" },
      { position: "九三", text: "家人嗃嗃，悔厉吉；妇子嘻嘻，终吝。", commentary: "家人嗃嗃，未失也；妇子嘻嘻，失家节也。" },
      { position: "六四", text: "富家，大吉。", commentary: "富家大吉，顺在位也。" },
      { position: "九五", text: "王假有家，勿恤，往吉。", commentary: "王假有家，交相爱也。" },
      { position: "上九", text: "有孚威如，终吉。", commentary: "威如之吉，反身之谓也。" },
    ],
  },
  {
    number: 38,
    name: "睽",
    symbol: "䷥",
    pinyin: "kui",
    upperTrigram: "离",
    lowerTrigram: "兑",
    judgment: "睽：小事吉。",
    image: "上火下泽，睽；君子以同而异。",
    lines: [
      { position: "初九", text: "悔亡，丧马勿逐，自复；见恶人无咎。", commentary: "见恶人，以辟咎也。" },
      { position: "九二", text: "遇主于巷，无咎。", commentary: "遇主于巷，未失道也。" },
      { position: "六三", text: "见舆曳，其牛掣，其人天且劓，无初有终。", commentary: "见舆曳，位不当也。无初有终，遇刚也。" },
      { position: "九四", text: "睽孤，遇元夫，交孚，厉无咎。", commentary: "交孚无咎，志行也。" },
      { position: "六五", text: "悔亡，厥宗噬肤，往何咎。", commentary: "厥宗噬肤，往有庆也。" },
      { position: "上九", text: "睽孤，见豕负涂，载鬼一车，先张之弧，后说之弧，匪寇婚媾，往遇雨则吉。", commentary: "遇雨之吉，群疑亡也。" },
    ],
  },
  {
    number: 39,
    name: "蹇",
    symbol: "䷦",
    pinyin: "jian",
    upperTrigram: "坎",
    lowerTrigram: "艮",
    judgment: "蹇：利西南，不利东北；利见大人，贞吉。",
    image: "山上有水，蹇；君子以反身修德。",
    lines: [
      { position: "初六", text: "往蹇，来誉。", commentary: "往蹇来誉，宜待也。" },
      { position: "六二", text: "王臣蹇蹇，匪躬之故。", commentary: "王臣蹇蹇，终无尤也。" },
      { position: "九三", text: "往蹇来反。", commentary: "往蹇来反，内喜之也。" },
      { position: "六四", text: "往蹇来连。", commentary: "往蹇来连，当位实也。" },
      { position: "九五", text: "大蹇朋来。", commentary: "大蹇朋来，以中节也。" },
      { position: "上六", text: "往蹇来硕，吉；利见大人。", commentary: "往蹇来硕，志在内也。利见大人，以从贵也。" },
    ],
  },
  {
    number: 40,
    name: "解",
    symbol: "䷧",
    pinyin: "jie",
    upperTrigram: "震",
    lowerTrigram: "坎",
    judgment: "解：利西南，无所往，其来复吉。有攸往，夙吉。",
    image: "雷雨作，解；君子以赦过宥罪。",
    lines: [
      { position: "初六", text: "无咎。", commentary: "刚柔之际，义无咎也。" },
      { position: "九二", text: "田获三狐，得黄矢，贞吉。", commentary: "九二贞吉，得中道也。" },
      { position: "六三", text: "负且乘，致寇至，贞吝。", commentary: "负且乘，亦可丑也，自我致戎，又谁咎也。" },
      { position: "九四", text: "解而拇，朋至斯孚。", commentary: "解而拇，未当位也。" },
      { position: "六五", text: "君子维有解，吉；有孚于小人。", commentary: "君子有解，小人退也。" },
      { position: "上六", text: "公用射隼于高墉之上，获之，无不利。", commentary: "公用射隼，以解悖也。" },
    ],
  },
  {
    number: 41,
    name: "损",
    symbol: "䷨",
    pinyin: "sun",
    upperTrigram: "艮",
    lowerTrigram: "兑",
    judgment: "损：有孚，元吉，无咎，可贞，利有攸往。曷之用，二簋可用享。",
    image: "山下有泽，损；君子以惩忿窒欲。",
    lines: [
      { position: "初九", text: "巳事遄往，无咎，酌损之。", commentary: "巳事遄往，尚合志也。" },
      { position: "九二", text: "利贞，征凶，弗损，益之。", commentary: "九二利贞，中以为志也。" },
      { position: "六三", text: "三人行，则损一人；一人行，则得其友。", commentary: "一人行，三则疑也。" },
      { position: "六四", text: "损其疾，使遄有喜，无咎。", commentary: "损其疾，亦可喜也。" },
      { position: "六五", text: "或益之，十朋之龟弗克违，元吉。", commentary: "六五元吉，自上佑也。" },
      { position: "上九", text: "弗损益之，无咎，贞吉，有攸往，得臣无家。", commentary: "弗损益之，大得志也。" },
    ],
  },
  {
    number: 42,
    name: "益",
    symbol: "䷩",
    pinyin: "yi1",
    upperTrigram: "巽",
    lowerTrigram: "震",
    judgment: "益：利有攸往。利涉大川。",
    image: "风雷，益；君子以见善则迁，有过则改。",
    lines: [
      { position: "初九", text: "利用为大作，元吉，无咎。", commentary: "元吉无咎，下不厚事也。" },
      { position: "六二", text: "或益之，十朋之龟弗克违，永贞吉。王用享于帝，吉。", commentary: "或益之，自外来也。" },
      { position: "六三", text: "益之用凶事，无咎。有孚中行，告公用圭。", commentary: "益用凶事，固有之也。" },
      { position: "六四", text: "中行，告公从。利用为依迁国。", commentary: "告公从，以益志也。" },
      { position: "九五", text: "有孚惠心，勿问元吉。有孚惠我德。", commentary: "有孚惠心，勿问之矣。惠我德，大得志也。" },
      { position: "上九", text: "莫益之，或击之，立心勿恒，凶。", commentary: "莫益之，偏辞也。或击之，自外来也。" },
    ],
  },
  {
    number: 43,
    name: "夬",
    symbol: "䷪",
    pinyin: "guai",
    upperTrigram: "兑",
    lowerTrigram: "乾",
    judgment: "夬：扬于王庭，孚号，有厉，告自邑，不利即戎，利有攸往。",
    image: "泽上于天，夬；君子以施禄及下，居德则忌。",
    lines: [
      { position: "初九", text: "壮于前趾，往不胜为咎。", commentary: "不胜而往，咎也。" },
      { position: "九二", text: "惕号，莫夜有戎，勿恤。", commentary: "莫夜有戎，得中道也。" },
      { position: "九三", text: "壮于頄，有凶。君子夬夬，独行，遇雨，若濡，有愠，无咎。", commentary: "君子夬夬，终无咎也。" },
      { position: "九四", text: "臀无肤，其行次且。牵羊悔亡，闻言不信。", commentary: "其行次且，位不当也。闻言不信，聪不明也。" },
      { position: "九五", text: "苋陆夬夬，中行无咎。", commentary: "中行无咎，中未光也。" },
      { position: "上六", text: "无号，终有凶。", commentary: "无号之凶，终不可长也。" },
    ],
  },
  {
    number: 44,
    name: "姤",
    symbol: "䷫",
    pinyin: "gou",
    upperTrigram: "乾",
    lowerTrigram: "巽",
    judgment: "姤：女壮，勿用取女。",
    image: "天下有风，姤；后以施命诰四方。",
    lines: [
      { position: "初六", text: "系于金柅，贞吉，有攸往，见凶，羸豕孚蹢躅。", commentary: "系于金柅，柔道牵也。" },
      { position: "九二", text: "包有鱼，无咎，不利宾。", commentary: "包有鱼，义不及宾也。" },
      { position: "九三", text: "臀无肤，其行次且，厉，无大咎。", commentary: "其行次且，行未牵也。" },
      { position: "九四", text: "包无鱼，起凶。", commentary: "无鱼之凶，远民也。" },
      { position: "九五", text: "以杞包瓜，含章，有陨自天。", commentary: "九五含章，中正也。有陨自天，志不舍命也。" },
      { position: "上九", text: "姤其角，吝，无咎。", commentary: "姤其角，上穷吝也。" },
    ],
  },
  {
    number: 45,
    name: "萃",
    symbol: "䷬",
    pinyin: "cui",
    upperTrigram: "兑",
    lowerTrigram: "坤",
    judgment: "萃：亨。王假有庙，利见大人，亨，利贞。用大牲吉，利有攸往。",
    image: "泽上于地，萃；君子以除戎器，戒不虞。",
    lines: [
      { position: "初六", text: "有孚不终，乃乱乃萃，若号一握为笑，勿恤，往无咎。", commentary: "乃乱乃萃，其志乱也。" },
      { position: "六二", text: "引吉，无咎，孚乃利用禴。", commentary: "引吉无咎，中未变也。" },
      { position: "六三", text: "萃如，嗟如，无攸利，往无咎，小吝。", commentary: "往无咎，上巽也。" },
      { position: "九四", text: "大吉，无咎。", commentary: "大吉无咎，位不当也。" },
      { position: "九五", text: "萃有位，无咎。匪孚，元永贞，悔亡。", commentary: "萃有位，志未光也。" },
      { position: "上六", text: "赍咨涕洟，无咎。", commentary: "赍咨涕洟，未安上也。" },
    ],
  },
  {
    number: 46,
    name: "升",
    symbol: "䷭",
    pinyin: "sheng",
    upperTrigram: "坤",
    lowerTrigram: "巽",
    judgment: "升：元亨，用见大人，勿恤，南征吉。",
    image: "地中生木，升；君子以顺德，积小以高大。",
    lines: [
      { position: "初六", text: "允升，大吉。", commentary: "允升大吉，上合志也。" },
      { position: "九二", text: "孚乃利用禴，无咎。", commentary: "九二之孚，有喜也。" },
      { position: "九三", text: "升虚邑。", commentary: "升虚邑，无所疑也。" },
      { position: "六四", text: "王用亨于岐山，吉无咎。", commentary: "王用亨于岐山，顺事也。" },
      { position: "六五", text: "贞吉，升阶。", commentary: "贞吉升阶，大得志也。" },
      { position: "上六", text: "冥升，利于不息之贞。", commentary: "冥升在上，消不富也。" },
    ],
  },
  {
    number: 47,
    name: "困",
    symbol: "䷮",
    pinyin: "kun1",
    upperTrigram: "兑",
    lowerTrigram: "坎",
    judgment: "困：亨，贞大人吉，无咎，有言不信。",
    image: "泽无水，困；君子以致命遂志。",
    lines: [
      { position: "初六", text: "臀困于株木，入于幽谷，三岁不觌。", commentary: "入于幽谷，幽不明也。" },
      { position: "九二", text: "困于酒食，朱绂方来，利用亨祀，征凶，无咎。", commentary: "困于酒食，中有庆也。" },
      { position: "六三", text: "困于石，据于蒺藜，入于其宫，不见其妻，凶。", commentary: "据于蒺藜，乘刚也。入于其宫，不见其妻，不祥也。" },
      { position: "九四", text: "来徐徐，困于金车，吝，有终。", commentary: "来徐徐，志在下也。虽不当位，有与也。" },
      { position: "九五", text: "劓刖，困于赤绂，乃徐有说，利用祭祀。", commentary: "劓刖，志未得也。乃徐有说，以中直也。利用祭祀，受福也。" },
      { position: "上六", text: "困于葛藟，于臲卼，曰动悔。有悔，征吉。", commentary: "困于葛藟，未当也。动悔，有悔，吉行也。" },
    ],
  },
  {
    number: 48,
    name: "井",
    symbol: "䷯",
    pinyin: "jing",
    upperTrigram: "坎",
    lowerTrigram: "巽",
    judgment: "井：改邑不改井，无丧无得，往来井井。汔至，亦未繘井，羸其瓶，凶。",
    image: "木上有水，井；君子以劳民劝相。",
    lines: [
      { position: "初六", text: "井泥不食，旧井无禽。", commentary: "井泥不食，下也。旧井无禽，时舍也。" },
      { position: "九二", text: "井谷射鲋，瓮敝漏。", commentary: "井谷射鲋，无与也。" },
      { position: "九三", text: "井渫不食，为我心恻，可用汲，王明，并受其福。", commentary: "井渫不食，行恻也。求王明，受福也。" },
      { position: "六四", text: "井甃，无咎。", commentary: "井甃无咎，修井也。" },
      { position: "九五", text: "井冽，寒泉食。", commentary: "寒泉之食，中正也。" },
      { position: "上六", text: "井收勿幕，有孚元吉。", commentary: "元吉在上，大成也。" },
    ],
  },
  {
    number: 49,
    name: "革",
    symbol: "䷰",
    pinyin: "ge",
    upperTrigram: "兑",
    lowerTrigram: "离",
    judgment: "革：巳日乃孚，元亨利贞，悔亡。",
    image: "泽中有火，革；君子以治历明时。",
    lines: [
      { position: "初九", text: "巩用黄牛之革。", commentary: "巩用黄牛，不可以有为也。" },
      { position: "六二", text: "巳日乃革之，征吉，无咎。", commentary: "巳日革之，行有嘉也。" },
      { position: "九三", text: "征凶，贞厉，革言三就，有孚。", commentary: "革言三就，又何之矣。" },
      { position: "九四", text: "悔亡，有孚改命，吉。", commentary: "改命之吉，信志也。" },
      { position: "九五", text: "大人虎变，未占有孚。", commentary: "大人虎变，其文炳也。" },
      { position: "上六", text: "君子豹变，小人革面，征凶，居贞吉。", commentary: "君子豹变，其文蔚也。小人革面，顺以从君也。" },
    ],
  },
  {
    number: 50,
    name: "鼎",
    symbol: "䷱",
    pinyin: "ding",
    upperTrigram: "离",
    lowerTrigram: "巽",
    judgment: "鼎：元吉，亨。",
    image: "木上有火，鼎；君子以正位凝命。",
    lines: [
      { position: "初六", text: "鼎颠趾，利出否，得妾以其子，无咎。", commentary: "鼎颠趾，未悖也。利出否，以从贵也。" },
      { position: "九二", text: "鼎有实，我仇有疾，不我能即，吉。", commentary: "鼎有实，慎所之也。我仇有疾，终无尤也。" },
      { position: "九三", text: "鼎耳革，其行塞，雉膏不食，方雨亏悔，终吉。", commentary: "鼎耳革，失其义也。" },
      { position: "九四", text: "鼎折足，覆公餗，其形渥，凶。", commentary: "覆公餗，信如何也。" },
      { position: "六五", text: "鼎黄耳，金铉，利贞。", commentary: "鼎黄耳，中以为实也。" },
      { position: "上九", text: "鼎玉铉，大吉，无不利。", commentary: "玉铉在上，刚柔节也。" },
    ],
  },
  {
    number: 51,
    name: "震",
    symbol: "䷲",
    pinyin: "zhen",
    upperTrigram: "震",
    lowerTrigram: "震",
    judgment: "震：亨。震来虩虩，笑言哑哑。震惊百里，不丧匕鬯。",
    image: "洊雷，震；君子以恐惧修省。",
    lines: [
      { position: "初九", text: "震来虩虩，后笑言哑哑，吉。", commentary: "震来虩虩，恐致福也。笑言哑哑，后有则也。" },
      { position: "六二", text: "震来厉，亿丧贝，跻于九陵，勿逐，七日得。", commentary: "震来厉，乘刚也。" },
      { position: "六三", text: "震苏苏，震行无眚。", commentary: "震苏苏，位不当也。" },
      { position: "九四", text: "震遂泥。", commentary: "震遂泥，未光也。" },
      { position: "六五", text: "震往来厉，亿无丧，有事。", commentary: "震往来厉，危行也。其事在中，大无丧也。" },
      { position: "上六", text: "震索索，视矍矍，征凶。震不于其躬，于其邻，无咎。婚媾有言。", commentary: "震索索，中未得也。虽凶无咎，畏邻戒也。" },
    ],
  },
  {
    number: 52,
    name: "艮",
    symbol: "䷳",
    pinyin: "gen",
    upperTrigram: "艮",
    lowerTrigram: "艮",
    judgment: "艮：艮其背，不获其身，行其庭，不见其人，无咎。",
    image: "兼山，艮；君子以思不出其位。",
    lines: [
      { position: "初六", text: "艮其趾，无咎，利永贞。", commentary: "艮其趾，未失正也。" },
      { position: "六二", text: "艮其腓，不拯其随，其心不快。", commentary: "不拯其随，未退听也。" },
      { position: "九三", text: "艮其限，列其夤，厉薰心。", commentary: "艮其限，危薰心也。" },
      { position: "六四", text: "艮其身，无咎。", commentary: "艮其身，止诸躬也。" },
      { position: "六五", text: "艮其辅，言有序，悔亡。", commentary: "艮其辅，以中正也。" },
      { position: "上九", text: "敦艮，吉。", commentary: "敦艮之吉，以厚终也。" },
    ],
  },
  {
    number: 53,
    name: "渐",
    symbol: "䷴",
    pinyin: "jian1",
    upperTrigram: "巽",
    lowerTrigram: "艮",
    judgment: "渐：女归吉，利贞。",
    image: "山上有木，渐；君子以居贤德，善俗。",
    lines: [
      { position: "初六", text: "鸿渐于干，小子厉，有言，无咎。", commentary: "小子之厉，义无咎也。" },
      { position: "六二", text: "鸿渐于磐，饮食衎衎，吉。", commentary: "饮食衎衎，不素饱也。" },
      { position: "九三", text: "鸿渐于陆，夫征不复，妇孕不育，凶；利御寇。", commentary: "夫征不复，离群丑也。妇孕不育，失其道也。利用御寇，顺相保也。" },
      { position: "六四", text: "鸿渐于木，或得其桷，无咎。", commentary: "或得其桷，顺以巽也。" },
      { position: "九五", text: "鸿渐于陵，妇三岁不孕，终莫之胜，吉。", commentary: "终莫之胜，吉；得所愿也。" },
      { position: "上九", text: "鸿渐于陆，其羽可用为仪，吉。", commentary: "其羽可用为仪，吉；不可乱也。" },
    ],
  },
  {
    number: 54,
    name: "归妹",
    symbol: "䷵",
    pinyin: "gui-mei",
    upperTrigram: "震",
    lowerTrigram: "兑",
    judgment: "归妹：征凶，无攸利。",
    image: "泽上有雷，归妹；君子以永终知敝。",
    lines: [
      { position: "初九", text: "归妹以娣，跛能履，征吉。", commentary: "归妹以娣，以恒也。跛能履吉，相承也。" },
      { position: "九二", text: "眇能视，利幽人之贞。", commentary: "利幽人之贞，未变常也。" },
      { position: "六三", text: "归妹以须，反归以娣。", commentary: "归妹以须，未当也。" },
      { position: "九四", text: "归妹愆期，迟归有时。", commentary: "愆期之志，有待而行也。" },
      { position: "六五", text: "帝乙归妹，其君之袂，不如其娣之袂良，月几望，吉。", commentary: "帝乙归妹，不如其娣之袂良也。其位在中，以贵行也。" },
      { position: "上六", text: "女承筐无实，士刲羊无血，无攸利。", commentary: "上六无实，承虚筐也。" },
    ],
  },
  {
    number: 55,
    name: "丰",
    symbol: "䷶",
    pinyin: "feng",
    upperTrigram: "震",
    lowerTrigram: "离",
    judgment: "丰：亨，王假之，勿忧，宜日中。",
    image: "雷电皆至，丰；君子以折狱致刑。",
    lines: [
      { position: "初九", text: "遇其配主，虽旬无咎，往有尚。", commentary: "虽旬无咎，过旬灾也。" },
      { position: "六二", text: "丰其蔀，日中见斗，往得疑疾，有孚发若，吉。", commentary: "有孚发若，信以发志也。" },
      { position: "九三", text: "丰其沛，日中见沬，折其右肱，无咎。", commentary: "丰其沛，不可大事也。折其右肱，终不可用也。" },
      { position: "九四", text: "丰其蔀，日中见斗，遇其夷主，吉。", commentary: "丰其蔀，位不当也。日中见斗，幽不明也。遇其夷主，吉；行也。" },
      { position: "六五", text: "来章，有庆誉，吉。", commentary: "六五之吉，有庆也。" },
      { position: "上六", text: "丰其屋，蔀其家，闚其户，阒其无人，三岁不觌，凶。", commentary: "丰其屋，天际翔也。闚其户，阒其无人，自藏也。" },
    ],
  },
  {
    number: 56,
    name: "旅",
    symbol: "䷷",
    pinyin: "lu1",
    upperTrigram: "离",
    lowerTrigram: "艮",
    judgment: "旅：小亨，旅贞吉。",
    image: "山上有火，旅；君子以明慎用刑，而不留狱。",
    lines: [
      { position: "初六", text: "旅琐琐，斯其所取灾。", commentary: "旅琐琐，志穷灾也。" },
      { position: "六二", text: "旅即次，怀其资，得童仆贞。", commentary: "得童仆贞，终无尤也。" },
      { position: "九三", text: "旅焚其次，丧其童仆，贞厉。", commentary: "旅焚其次，亦以伤矣。以旅与下，其义丧也。" },
      { position: "九四", text: "旅于处，得其资斧，我心不快。", commentary: "旅于处，未得位也。得其资斧，心未快也。" },
      { position: "六五", text: "射雉一矢亡，终以誉命。", commentary: "终以誉命，上逮也。" },
      { position: "上九", text: "鸟焚其巢，旅人先笑后号啕。丧牛于易，凶。", commentary: "以旅在上，其义焚也。丧牛于易，终莫之闻也。" },
    ],
  },
  {
    number: 57,
    name: "巽",
    symbol: "䷸",
    pinyin: "xun",
    upperTrigram: "巽",
    lowerTrigram: "巽",
    judgment: "巽：小亨，利攸往，利见大人。",
    image: "随风，巽；君子以申命行事。",
    lines: [
      { position: "初六", text: "进退，利武人之贞。", commentary: "进退，志疑也。利武人之贞，志治也。" },
      { position: "九二", text: "巽在床下，用史巫纷若，吉，无咎。", commentary: "纷若之吉，得中也。" },
      { position: "九三", text: "频巽，吝。", commentary: "频巽之吝，志穷也。" },
      { position: "六四", text: "悔亡，田获三品。", commentary: "田获三品，有功也。" },
      { position: "九五", text: "贞吉悔亡，无不利。无初有终，先庚三日，后庚三日，吉。", commentary: "九五之吉，位正中也。" },
      { position: "上九", text: "巽在床下，丧其资斧，贞凶。", commentary: "巽在床下，上穷也。丧其资斧，正乎凶也。" },
    ],
  },
  {
    number: 58,
    name: "兑",
    symbol: "䷹",
    pinyin: "dui",
    upperTrigram: "兑",
    lowerTrigram: "兑",
    judgment: "兑：亨，利贞。",
    image: "丽泽，兑；君子以朋友讲习。",
    lines: [
      { position: "初九", text: "和兑，吉。", commentary: "和兑之吉，行未疑也。" },
      { position: "九二", text: "孚兑，吉，悔亡。", commentary: "孚兑之吉，信志也。" },
      { position: "六三", text: "来兑，凶。", commentary: "来兑之凶，位不当也。" },
      { position: "九四", text: "商兑，未宁，介疾有喜。", commentary: "九四之喜，有庆也。" },
      { position: "九五", text: "孚于剥，有厉。", commentary: "孚于剥，位正当也。" },
      { position: "上六", text: "引兑。", commentary: "上六引兑，未光也。" },
    ],
  },
  {
    number: 59,
    name: "涣",
    symbol: "䷺",
    pinyin: "huan",
    upperTrigram: "巽",
    lowerTrigram: "坎",
    judgment: "涣：亨。王假有庙，利涉大川，利贞。",
    image: "风行水上，涣；先王以享于帝立庙。",
    lines: [
      { position: "初六", text: "用拯马壮，吉。", commentary: "初六之吉，顺也。" },
      { position: "九二", text: "涣奔其机，悔亡。", commentary: "涣奔其机，得愿也。" },
      { position: "六三", text: "涣其躬，无悔。", commentary: "涣其躬，志在外也。" },
      { position: "六四", text: "涣其群，元吉。涣有丘，匪夷所思。", commentary: "涣其群，元吉；光大也。" },
      { position: "九五", text: "涣汗其大号，涣王居，无咎。", commentary: "王居无咎，正位也。" },
      { position: "上九", text: "涣其血，去逖出，无咎。", commentary: "涣其血，远害也。" },
    ],
  },
  {
    number: 60,
    name: "节",
    symbol: "䷻",
    pinyin: "jie1",
    upperTrigram: "坎",
    lowerTrigram: "兑",
    judgment: "节：亨。苦节不可贞。",
    image: "泽上有水，节；君子以制数度，议德行。",
    lines: [
      { position: "初九", text: "不出户庭，无咎。", commentary: "不出户庭，知通塞也。" },
      { position: "九二", text: "不出门庭，凶。", commentary: "不出门庭，失时极也。" },
      { position: "六三", text: "不节若，则嗟若，无咎。", commentary: "不节之嗟，又谁咎也。" },
      { position: "六四", text: "安节，亨。", commentary: "安节之亨，承上道也。" },
      { position: "九五", text: "甘节，吉；往有尚。", commentary: "甘节之吉，居位中也。" },
      { position: "上六", text: "苦节，贞凶，悔亡。", commentary: "苦节贞凶，其道穷也。" },
    ],
  },
  {
    number: 61,
    name: "中孚",
    symbol: "䷼",
    pinyin: "zhong-fu",
    upperTrigram: "巽",
    lowerTrigram: "兑",
    judgment: "中孚：豚鱼吉，利涉大川，利贞。",
    image: "泽上有风，中孚；君子以议狱缓死。",
    lines: [
      { position: "初九", text: "虞吉，有它不燕。", commentary: "初九虞吉，志未变也。" },
      { position: "九二", text: "鸣鹤在阴，其子和之，我有好爵，吾与尔靡之。", commentary: "其子和之，中心愿也。" },
      { position: "六三", text: "得敌，或鼓或罢，或泣或歌。", commentary: "可鼓或罢，位不当也。" },
      { position: "六四", text: "月几望，马匹亡，无咎。", commentary: "马匹亡，绝类上也。" },
      { position: "九五", text: "有孚挛如，无咎。", commentary: "有孚挛如，位正当也。" },
      { position: "上九", text: "翰音登于天，贞凶。", commentary: "翰音登于天，何可长也。" },
    ],
  },
  {
    number: 62,
    name: "小过",
    symbol: "䷽",
    pinyin: "xiao-guo",
    upperTrigram: "震",
    lowerTrigram: "艮",
    judgment: "小过：亨，利贞，可小事，不可大事。飞鸟遗之音，不宜上，宜下，大吉。",
    image: "山上有雷，小过；君子以行过乎恭，丧过乎哀，用过乎俭。",
    lines: [
      { position: "初六", text: "飞鸟以凶。", commentary: "飞鸟以凶，不可如何也。" },
      { position: "六二", text: "过其祖，遇其妣；不及其君，遇其臣；无咎。", commentary: "不及其君，臣不可过也。" },
      { position: "九三", text: "弗过防之，从或戕之，凶。", commentary: "从或戕之，凶如何也。" },
      { position: "九四", text: "无咎，弗过遇之。往厉必戒，勿用永贞。", commentary: "弗过遇之，位不当也。往厉必戒，终不可长也。" },
      { position: "六五", text: "密云不雨，自我西郊，公弋取彼在穴。", commentary: "密云不雨，已上也。" },
      { position: "上六", text: "弗遇过之，飞鸟离之，凶，是谓灾眚。", commentary: "弗遇过之，已亢也。" },
    ],
  },
  {
    number: 63,
    name: "既济",
    symbol: "䷾",
    pinyin: "ji-ji",
    upperTrigram: "坎",
    lowerTrigram: "离",
    judgment: "既济：亨，小利贞，初吉终乱。",
    image: "水在火上，既济；君子以思患而预防之。",
    lines: [
      { position: "初九", text: "曳其轮，濡其尾，无咎。", commentary: "曳其轮，义无咎也。" },
      { position: "六二", text: "妇丧其茀，勿逐，七日得。", commentary: "七日得，以中道也。" },
      { position: "九三", text: "高宗伐鬼方，三年克之，小人勿用。", commentary: "三年克之，惫也。" },
      { position: "六四", text: "繻有衣袽，终日戒。", commentary: "终日戒，有所疑也。" },
      { position: "九五", text: "东邻杀牛，不如西邻之禴祭，实受其福。", commentary: "东邻杀牛，不如西邻之时也；实受其福，吉大来也。" },
      { position: "上六", text: "濡其首，厉。", commentary: "濡其首厉，何可久也。" },
    ],
  },
  {
    number: 64,
    name: "未济",
    symbol: "䷿",
    pinyin: "wei-ji",
    upperTrigram: "离",
    lowerTrigram: "坎",
    judgment: "未济：亨，小狐汔济，濡其尾，无攸利。",
    image: "火在水上，未济；君子以慎辨物居方。",
    lines: [
      { position: "初六", text: "濡其尾，吝。", commentary: "濡其尾，亦不知极也。" },
      { position: "九二", text: "曳其轮，贞吉。", commentary: "九二贞吉，中以行正也。" },
      { position: "六三", text: "未济，征凶，利涉大川。", commentary: "未济征凶，位不当也。" },
      { position: "九四", text: "贞吉，悔亡，震用伐鬼方，三年有赏于大国。", commentary: "贞吉悔亡，志行也。" },
      { position: "六五", text: "贞吉，无悔，君子之光，有孚，吉。", commentary: "君子之光，其晖吉也。" },
      { position: "上九", text: "有孚于饮酒，无咎，濡其首，有孚失是。", commentary: "饮酒濡首，亦不知节也。" },
    ],
  },
];
